//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.15 at 03:00:21 PM CEST 
//


package haas.olivier.comptes.dao.xml.jaxb.perm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the haas.olivier.comptes.dao.xml.jaxb.perm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: haas.olivier.comptes.dao.xml.jaxb.perm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Jours.Jour }
     * 
     */
    public Jours.Jour createJoursJour() {
        return new Jours.Jour();
    }

    /**
     * Create an instance of {@link Montants.Montant }
     * 
     */
    public Montants.Montant createMontantsMontant() {
        return new Montants.Montant();
    }

    /**
     * Create an instance of {@link Permanents }
     * 
     */
    public Permanents createPermanents() {
        return new Permanents();
    }

    /**
     * Create an instance of {@link Montants }
     * 
     */
    public Montants createMontants() {
        return new Montants();
    }

    /**
     * Create an instance of {@link Permanent.Dependance }
     * 
     */
    public Permanent.Dependance createPermanentDependance() {
        return new Permanent.Dependance();
    }

    /**
     * Create an instance of {@link Permanent }
     * 
     */
    public Permanent createPermanent() {
        return new Permanent();
    }

    /**
     * Create an instance of {@link Jours }
     * 
     */
    public Jours createJours() {
        return new Jours();
    }

}
