//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.15 at 03:00:21 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:haas.olivier.comptes.permanents", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package haas.olivier.comptes.dao.xml.jaxb.perm;
